#pragma once

#include "Node.h"
#include "FileNode.h"
#include "IMonitoredProcess.h"
#include "MemoryLogBook.h"
#include "../xxHash/xxhash.h"

#include <atomic>

namespace YAM
{
    class GeneratedFileNode;

    // CommandNode is capable of:
    //    - executing a shell script with a given set of output files.
    //    - detecting which files are accessed during the execution of the script.
    //    - checking that the write-accessed files match the output files.
    //    - registering the detected read-accessed files as input files.
    //    - detecting changes in script, input and/or output files.
    //      Such changes will out-date the outputs of the command node, causing 
    //      pendingStartSelf() to return true.
    // 
    // CommandNode ignores input files that are not contained in one of the
    // file repositories registered in the execution context.
    // Otherwise the CommandNode registers a file node associated with the 
    // input file in the command node's input set. It will create such a 
    // file node and add it to the execution context if the node did not yet
    // exist.
    //      
    class __declspec(dllexport) CommandNode : public Node
    {
    public:
        typedef std::map<std::filesystem::path, std::shared_ptr<FileNode>> InputNodes;

        CommandNode(); // needed for deserialization
        CommandNode(ExecutionContext* context, std::filesystem::path const& name);
        ~CommandNode();
        
        bool supportsPrerequisites() const override;

        // getPrerequisites appends to given 'prerequisites:
        //   - The input producers (CommandNodes).
        //   - The source files (SourceFileNodes) in the command's input nodes.
        //   - The command's output files (GeneratedFileNodes).
        // Source and output file nodes are prerequisites because their 
        // executions compute file hashes that are used by pendingStartSelf to
        // check whether source inputs were modified and/or outputs have been
        // tampered with. pendingStartSelf also uses the hashes of input files
        // that were generated by the input producers. The input producers are
        // therefore also included in 'prerequisites'to make sure that these
        // generated input files are up-to-date.
        void getPrerequisites(std::vector<std::shared_ptr<Node>>& prerequisites) const override;

        bool supportsOutputs() const override;
        void getOutputs(std::vector<std::shared_ptr<Node>>& outputs) const override;

        bool supportsInputs() const override;
        void getInputs(std::vector<std::shared_ptr<Node>>& inputs) const override;

        bool pendingStartSelf() const override;

        void cancelSelf() override;

        // Set the input file aspects that contribute to the output file(s)
        // of the command node.
        void setInputAspectsName(std::string const& newName);

        // Set the output files generated by this node's execution.
        void setOutputs(std::vector<std::shared_ptr<GeneratedFileNode>> const & newOutputs);

        // Set the shell script to be executed when this node executes.
        // The script must generate all the files specified by setOutputs.
        // Node execution will fail otherwise.
        void setScript(std::string const & newScript);

        // Set nodes that produce outputs that are (allowed to be) used as
        // inputs by this node. The producer nodes must be executed before this 
        // node to make sure that their outputs exist and are up-to-date.
        // Besides these generated inputs this node is also allowed to use 
        // source files as inputs. Source files need not be in newInputProducers.
        // Do not confuse source files with 'source files' generated from e.g.
        // IDL files, yacc and lex files. The nodes that generate such files must
        // be in newIputProducers.
        // This node does not take ownership of the producer nodes.
        void setInputProducers(std::vector<std::shared_ptr<Node>> const & newInputProducers);

        void getInputProducers(std::vector<std::shared_ptr<Node>>& producers) const;

        static void setStreamableType(uint32_t type);
        // Inherited from IStreamable
        uint32_t typeId() const override;
        void stream(IStreamer* streamer) override;
        // Inherited from IPersistable
        void prepareDeserialize() override;
        void restore(void* context) override;

    protected:
        void selfExecute() override;

    private:
        struct ExecutionResult : public Node::SelfExecutionResult {
            std::set<std::filesystem::path> _outputPaths;
            std::set<std::filesystem::path> _keptInputPaths;
            std::set<std::filesystem::path> _removedInputPaths;
            std::set<std::filesystem::path> _addedInputPaths;
            std::vector<std::shared_ptr<FileNode>> _addedInputNodes;
        };

        void getSourceInputs(std::vector<std::shared_ptr<Node>> & sourceInputs) const;
        void setInputs(ExecutionResult const& result);
        XXH64_hash_t computeExecutionHash() const;

        std::shared_ptr<GeneratedFileNode> findOutputNode(
            std::filesystem::path const& output,
            MemoryLogBook& logBook);
        bool findOutputNodes(
            std::set<std::filesystem::path> const& outputPaths,
            std::vector<std::shared_ptr<GeneratedFileNode>>& outputNodes,
            MemoryLogBook& logBook);
        bool verifyOutputNodes(
            std::vector<std::shared_ptr<GeneratedFileNode>> const& newOutputs,
            MemoryLogBook& logBook);

        bool findInputNodes(
            std::map<std::filesystem::path, std::shared_ptr<GeneratedFileNode>> const& allowedGenInputFiles,
            std::set<std::filesystem::path>const& inputPaths,
            std::vector<std::shared_ptr<FileNode>>& inputNodes,
            std::vector<std::shared_ptr<Node>>& dirtyInputNodes,
            ILogBook& logBook
        );

        MonitoredProcessResult executeScript(MemoryLogBook& logBook); 

        void getPreCommitNodes(
            SelfExecutionResult& result,
            std::vector<std::shared_ptr<Node>>& preCommitNodes) override;
        void commitSelfCompletion(SelfExecutionResult const& result) override;

        // The name of the FileAspectSet that contains the aspects relevant for this
        // command, i.e. the aspects of input files that contribute to output file content.
        std::string _inputAspectsName;

        std::vector<std::shared_ptr<Node>> _inputProducers;
        std::vector<std::shared_ptr<GeneratedFileNode>> _outputs;

        // TODO: decide whether script will be streamed to build state.
        // Script can be large, e.g. a link script that links many object
        // files. Not streaming the script implies that all build files need 
        // to be reparsed to re-initialize command scripts. A change in 
        // script can then be detected by comparing its hash with hash 
        // of previous script (that was streamed to build state).
        std::string _script; 

        std::atomic<std::shared_ptr<IMonitoredProcess>> _scriptExecutor;
        
        // inputs detected during last script execution
        InputNodes _inputs;

        // The hash of the hashes of all items that, when changed, invalidate
        // the output files. Items include the script, the output files and 
        // the relevant aspects of the input files.
        XXH64_hash_t _executionHash;
    };
}
