#pragma once
#include "FileNode.h"

namespace YAM
{
    class __declspec(dllexport) GeneratedFileNode : public FileNode
    {
    public:
        // Construct a generated file node for the file identified by given 
        // 'name' and generated by given 'producer' (e.g. a command node).
        GeneratedFileNode(
            ExecutionContext* context, 
            std::filesystem::path const& name, 
            Node* producer);

        virtual void setState(State newState) override;

        Node* producer() const;
        bool deleteFile();

    private:
        Node* _producer;
    };
}
